server:
  port: 8081 # 端口

spring:
  application:
    name: ms-dinners # 应用名
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/tb_food?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  # Redis
  redis:
    port: 6379
    host: localhost
    timeout: 3000
    database: 1
    password:
  # swagger
  swagger:
    base-package: com.imooc.dinners
    title: 慕课美食社交食客API接口文档

# Oauth2
oauth2:
  client:
    client-id: appId
    secret: 123456
    grant_type: password
    scope: api

#oauth2服务地址
service:
  name:
    ms-oauth-server: http://ms-oauth2-server/

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'